### ISSUE TITLE
app disapear

### ISSUE THREAD

**Issue by slein35** [bnorick/labbie#12]
when i download and extract the file, i can launch the app labbie then windows opens a window where i need to execute it and then it loads and the app disappear from the folder and can't get it back / use it. re extract re launch the app and disappear again

**Comment by slein35** [comment]
Chemin d’accès de l’application défaillante : C:\Users\Niels\Downloads\Labbie\Labbie.exe
Chemin d’accès du module défaillant: C:\Users\Niels\Downloads\Labbie\lib\PyQt5\Qt5Core.dll
ID de rapport : 5b12449c-04ee-4fde-9e3c-fba12d0ac36c

this is the event viewer error that causes the crash

**Comment by bnorick** [comment]
To me this sounds like virus "protection" deciding to delete some/all of Labbie. Can you try to either whitelist the path to Labbie or temporarily disable your virus scan?

**Comment by slein35** [comment]
tried this and worked thanks
