### ISSUE TITLE
File Access Restricted After Extract

### ISSUE THREAD

**Issue by xintropy** [bnorick/labbie#13]
Hello,

After downloading the zip and extracting the file, I experience access issues on an administrator account. I've tried to look through different possibilities that would be causing the app to not download (sharing access, removing access requirements, running as admin, etc.) but I cannot find a solution. I have not had this issue with other downloaded apps. Could this be caused by something on the back end or most likely related to a setting I have but have not found?

**Comment by bnorick** [comment]
My first guess would be to check your virus scan. Try disabling it and running Labbie. If that works, find a way to whitelist the location you'll extract Labbie so that you don't have to leave it disabled.

**Comment by xintropy** [comment]
Seems to have worked, thanks for the tip.

**Comment by bnorick** [comment]
What virus scan are you using, out of curiosity? Windows defender doesn't flag Labbie, but I've seen a few reports of this recently.

Without getting a code signing cert, I don't think there is anything I can really do which is annoying.

**Comment by xintropy** [comment]
I'm using Avast. It was just a strange interaction with permissions or security flag that I was unfamiliar with.

**Comment by bnorick** [comment]
Great, thanks!
