### ISSUE TITLE
Install Help

### ISSUE THREAD

**Issue by roberthassler** [bnorick/labbie#18]
Hello, I saw labbie being used and I was hoping to be able to try it out for the 3.17 league. Any instructions on how to install?
Also, I respect the costs associated with hosting your own project and will happily contribute if I can figure this out. Thank you!

**Comment by dermow** [comment]
Heyho! Just visit the Release page -> [here](https://github.com/bnorick/labbie/releases). There you can download the latest stable release, extract it to any location you want and start it with Labbie.exe

**Comment by bnorick** [comment]
Thanks @dermow, that covers it! I'll try to remember to add these details to the README.

**Comment by dermow** [comment]
> Thanks @dermow, that covers it! I'll leave this open so I remember to add these details to the README.

 Created PR  #19 :)

**Comment by roberthassler** [comment]
That helped. Appreciate it. Got it installed, tested it out. Looks great. Thank you for your support.
