### ISSUE TITLE
TimeoutError when starting labbie

### ISSUE THREAD

**Issue by kuselfoo** [bnorick/labbie#24]
Hi,
when I try to start labbie, I get a timeout error from `src\labbie\resources.py` in line 82.
It looks like it tries to access `https://labbie.blob.core.windows.net/resources` for an update, but this URL is not reachable.

Edit: I also noticed that I do not have a labbie icon in windows next to the watch.

**Comment by bnorick** [comment]
I can't reproduce this with a fresh copy of 0.6.2.

Labbie accesses three urls with the prefix you mentioned,
- https://labbie.blob.core.windows.net/resources/pathofexile/1/stats.json.gz
- https://labbie.blob.core.windows.net/resources/pathofexile/1/items.json.gz
- https://labbie.blob.core.windows.net/resources/repoe/1/mods.json.gz

Check if you can access those manually, you should be able to. A manual workaround might be to put these in your `Labbie/data/resources` folder, but if you can't access them at all then that probably won't work either.

**Comment by kuselfoo** [comment]
I'm sorry. You were right. It was on my end. My firewall blocked all traffic from windows.net.
Now it's working like a charm. Thank you 👍
