### ISSUE TITLE
Labbie tries to search for the wrong "purity of elements" enchant when trying to price check; returning zero hits when opening web page

### ISSUE THREAD

**Issue by polo2005x** [bnorick/labbie#39]
Topic, 
link generated during price check: 
https://www.pathofexile.com/trade/search/Crucible/4elzD48I9

should be the other enchant:
https://www.pathofexile.com/trade/search/Crucible/6gwGBQbUG

**Comment by bnorick** [comment]
Use the latest prerelease, this has been fixed.

**Comment by polo2005x** [comment]
Sorry for my ignorance but; As in just downloading the project? or where do I find the prerelease?

**Comment by bnorick** [comment]
https://github.com/bnorick/labbie/releases/tag/v0.6.8-alpha.2
