### ISSUE TITLE
Can't start Labbie after several reinstalls

### ISSUE THREAD

**Issue by roberthuber16** [bnorick/labbie#40]
![image](https://user-images.githubusercontent.com/3967779/235319920-46859c5b-e931-4f21-8aea-3241dda24206.png)

**Comment by roberthuber16** [comment]
My apologies i see this is the exact same issue as https://github.com/bnorick/labbie/issues/34 

I dont ever see a resolution on that though

**Comment by roberthuber16** [comment]
Closing due to being able to load app on 6.5

**Comment by bnorick** [comment]
What do you mean by 6.5, so I know going forward?
