### ISSUE TITLE
Unable to get Lab enchant info

### ISSUE THREAD

**Issue by TerminalLife421125** [bnorick/labbie#41]
![J2dH0zF](https://user-images.githubusercontent.com/132217347/235363454-71d7242a-d97a-4c76-817b-202b14e54c0c.png)

**Comment by alex-gillies** [comment]
Also seeing this

**Comment by roberthuber16** [comment]
I am also on version 6.5 (can't do newer versions due to another error).

**Comment by bnorick** [comment]
Let's try to resolve what's wrong with newer versions, @roberthuber16 can you give me more details? What version of Windows are you on, etc.

Thanks!

**Comment by flashMK** [comment]
same error on latest version

**Comment by bnorick** [comment]
The difference here is that there are no longer daily stats on poeninja. While I may calculate them myself in the future, for now I simply disabled them and they are not available.

I resolved the packaging issue some users faced, so I'll do a release for 0.6.8 today.
